DELETE FROM trs;
LOAD DATA LOCAL
INFILE './processed.allTx.csv'
INTO TABLE trs
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
UPDATE trs SET debit = NULL WHERE debit = 0;
UPDATE trs SET credit = NULL WHERE credit = 0;
UPDATE trs SET balance = NULL WHERE balance = 0;
